### ISSUE TITLE
Opening terminal in Windows with a folder doesn't change the drive

### ISSUE THREAD

**Issue by bundyo** [nteract/term-launcher#15]
This can be avoided with /d option of the CD command, like this:
```
cmd /k cd /d d:\folder
```

**Comment by lgeiger** [comment]
Do you want to open a PR for this? I don't have a Windows machine so it's tricky for me to test cross platform. 😄

**Comment by Aaronmacaron** [comment]
This issue was fixed by #18 and the problem doesn't exist anymore. So I think this can be closed.
